AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM project template
Resources:
  retriever:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: retriever
      Handler: retriever.handler
      Runtime: nodejs12.x
      CodeUri: s3://djordje-test-sam/ba6b2ccdb49d2cfc9cf442df3bf69f21
      Description: Scans the DynamoDB table and returns results in response to API
        GET request.
      Policies:
      - DynamoDBCrudPolicy:
          TableName: transactions
      Events:
        ApiGET:
          Type: Api
          Properties:
            Path: /messages
            Method: GET
  transactionCreator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: transaction_creator
      Description: Polls the parsed_messages queue and writes data to DynamoDB table
      Handler: transaction_creator.handler
      Runtime: nodejs12.x
      CodeUri: s3://djordje-test-sam/ba6b2ccdb49d2cfc9cf442df3bf69f21
      Environment:
        Variables:
          TABLE_NAME: transactions
          PRIMARY_KEY: uuid
      Policies:
      - DynamoDBCrudPolicy:
          TableName: transactions
      Events:
        parsedMessagesSQS:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - ParsedMessages
              - Arn
  hbProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hb_processor
      Description: Periodically polls an SQS queue and asynchronously consumes each
        message.
      Handler: hb_processor.handler
      Runtime: nodejs12.x
      CodeUri: s3://djordje-test-sam/ba6b2ccdb49d2cfc9cf442df3bf69f21
      Policies:
      - SQSPollerPolicy:
          QueueName: hb_message_processing_queue
      Events:
        hbMessagesSQS:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - QueueHb
              - Arn
  nlbProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nlb_processor
      Description: Periodically polls an SQS queue and asynchronously consumes each
        message.
      Handler: nlb_processor.handler
      Runtime: nodejs12.x
      CodeUri: s3://djordje-test-sam/ba6b2ccdb49d2cfc9cf442df3bf69f21
      Policies:
      - SQSPollerPolicy:
          QueueName: nlb_message_processing_queue
      Events:
        hbMessagesSQS:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - QueueNlb
              - Arn
  router:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: router
      Description: Analyzes the incoming message on API and re-routes it depending
        on the content to one of the two queues.
      Handler: router.handler
      Runtime: nodejs12.x
      CodeUri: s3://djordje-test-sam/ba6b2ccdb49d2cfc9cf442df3bf69f21
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sqs:GetQueueAttributes
          - sqs:SendMessage
          Resource:
          - Fn::Join:
            - ':'
            - - arn:aws:sqs
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - hb_message_processing_queue
          - Fn::Join:
            - ':'
            - - arn:aws:sqs
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - nlb_message_processing_queue
      Events:
        transactionsApi:
          Type: Api
          Properties:
            Path: /messages
            Method: POST
  transactions:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transactions
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  QueueHb:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: hb_message_processing_queue
  QueueNlb:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: nlb_message_processing_queue
  ParsedMessages:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: parsed_messages
